### ISSUE TITLE
more flexible caching?

### ISSUE THREAD

**Issue by eribul** [johnmyleswhite/ProjectTemplate#147]
I would suggest to allow some flexibility for cachnig (just to pass a `...`to save would be a atsrt). I sometimes like to pass argument `compress = FALSE` when I work with large data sets and it takes a lot of time to compress/decompress.
I might also prefer `saveRDS` to `save`.

**Comment by KentonWhite** [comment]
I hadn't really thought about the choice of defaults for caching. It does make sense to allow some flexibility. I think passing in arguments to `cache` would be the easiest (rather than controlling the default behavior through the global.config file).

Is this a feature you might be willing to try implementing?

**Comment by connectedblue** [comment]
I have proposed a change #152 which enables objects in munge scripts to be cached only if they don't already exist.  This saves time during subsequent load.project() calls, especially for large transformations that can take a while to cache and usually you haven't made any changes.

If you have created a dataframe called `foo` from the raw datasets, you can have the command:
`cache("foo", always=FALSE)`
in a script which will save the `foo` object the first time, but will skip the caching step in subsequent runs.  Of course, if you change the logic that creates `foo`, you will want to refresh the cache.  In this case, the call
`clear.cache("foo")`
will delete that item from the cache, forcing the `foo` variable to be re-cached next time load.project() is run.

**Comment by KentonWhite** [comment]
I like this a lot and think it is a great step toward more flexible caching. Really like the addition of `clear.cache`. It is so much safer than manually deleting cached files. 

@connectedblue what do you think about adding a helper function `is.cached` that can be used to skip munging steps completely if the object exists in the cache? 

```
if(!is.cached("foo")) {
  # Expensive munging operation
}

**Comment by connectedblue** [comment]
Yes, the `is.cached()` will be very helpful.  I'll add that into the branch.

**Comment by connectedblue** [comment]
Actually, I think there is more to this than just this function.  The user still has to write the boiler code to test if it exists, do the processing and then cache with `always=FALSE`.

I think there is a further helper function that can do all that, plus emit warnings if the lines are skipped because the item is already cached, which would be helpful to remind if the user forgot to clear the cache when they changed some munge logic for that variable.

Something like:

`
dynamic.cache(var, {
      # Expensive munging operations
})
`

Again, I'll work up some code to demonstrate the context.  With an interface like this, you can start to do some smart caching functions like re-run the munge logic if the hash of the code block has changed compared to the value in the cache (as discussed in #80)

**Comment by KentonWhite** [comment]
Looking forward to seeing the interface you come up with. Think the idea of `dynamic.cache` is on the right track.

**Comment by connectedblue** [comment]
I've just proposed some code to implement this idea in #155

**Comment by connectedblue** [comment]
@eribul did you get a chance to look at pr #155?

I'm interested in your comments and whether it helps with the caching problems you have encountered?

**Comment by eribul** [comment]
Hi @connectedblue!

I'm sorry for my very late respond but my  life has been a little up-side down (I just became a father :-) 
I think all of this sounds realy great and exciting! I think it will be a great step forward!

**Comment by connectedblue** [comment]
Congratulations @eribul!  I don't suppose you will have too much time for R in the near future, but if you do very a chance, make sure you sync with the current `master` branch and check out lots of new features.

**Comment by connectedblue** [comment]
@KentonWhite Can this issue be closed now since the caching got merged in #155 ?

**Comment by KentonWhite** [comment]
Closed. Thanks for the reminder.
